version: "3.3"

services:
  web:
    image: andimajore/mesidha_frontend:latest
    container_name: mesidha_frontend
    ports:
      - "8041:80"
    restart: always
  app:
    image: andimajore/mesidha_backend:latest
    container_name: mesidha_backend
    env_file:
      - 'docker-django.env.dev'
    restart: always
    command:
      - "sh"
      - "/usr/src/mesidha/scripts/start_app.sh"
    ports:
      - "8042:8000"
    networks:
      - mesidha_net
    depends_on:
      - db
      - redis
  redis:
    image: redis
    restart: always
    command: [ "redis-server" ]
    container_name: mesidha_redis
    hostname: mesidha_redis
    networks:
      - mesidha_net
    depends_on:
      - db
  celery:
    command:
      - "sh"
      - "/usr/src/mesidha/scripts/start_celery_worker.sh"
    restart: always
    image: andimajore/mesidha_backend:latest
    container_name: mesidha_celery
    hostname: mesidha_celery
    env_file:
      - 'docker-django.env.dev'
    volumes:
      - mesidha_volume:/usr/src/mesidha/mapping_files
    depends_on:
      - redis
      - db
    networks:
      - mesidha_net
  celery-beat:
    command:
      - "sh"
      - "/usr/src/mesidha/scripts/start_celery_beat.sh"
    image: andimajore/mesidha_backend:latest
    container_name: mesidha_celery_beat
    hostname: mesidha_celery_beat
    env_file:
      - 'docker-django.env.dev'
    depends_on:
      - redis
      - db
    networks:
      - mesidha_net
  db:
    image: postgres
    restart: always
    container_name: mesidha_db
    hostname: db
    networks:
      - mesidha_net
    volumes:
      - mesidha_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mesidha
      - POSTGRES_USER=mesidhas
      - POSTGRES_PASSWORD=9ECDPWD8RWLtrNbmBVW6SSHw
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=2GB"

networks:
  mesidha_net:

volumes:
  mesidha_volume:
  mesidha_db_volume:
