version: "3.3"

services:
  web:
    image: andimajore/proharmed_frontend:latest
    container_name: proharmed_frontend
    ports:
      - "8111:80"
    restart: always
  app:
    image: andimajore/proharmed_backend:latest
    container_name: proharmed_backend
    env_file:
      - 'docker-django.env.dev'
    restart: always
    command:
      - "sh"
      - "/usr/src/proharmed/scripts/start_app.sh"
    ports:
      - "8112:8000"
    networks:
      - proharmed_net
    depends_on:
      - db
      - redis
  redis:
    image: redis
    restart: always
    command: [ "redis-server" ]
    container_name: proharmed_redis
    hostname: proharmed_redis
    networks:
      - proharmed_net
    depends_on:
      - db
  celery:
    command:
      - "sh"
      - "/usr/src/proharmed/scripts/start_celery_worker.sh"
    restart: always
    image: andimajore/proharmed_backend:latest
    container_name: proharmed_celery
    hostname: proharmed_celery
    env_file:
      - 'docker-django.env.dev'
    volumes:
      - proharmed_volume:/usr/src/proharmed/mapping_files
    depends_on:
      - redis
      - db
    networks:
      - proharmed_net
  celery-beat:
    command:
      - "sh"
      - "/usr/src/proharmed/scripts/start_celery_beat.sh"
    image: andimajore/proharmed_backend:latest
    container_name: proharmed_celery_beat
    hostname: proharmed_celery_beat
    env_file:
      - 'docker-django.env.dev'
    depends_on:
      - redis
      - db
    networks:
      - proharmed_net
  db:
    image: postgres
    restart: always
    container_name: proharmed_db
    hostname: db
    networks:
      - proharmed_net
    volumes:
      - proharmed_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=proharmed
      - POSTGRES_USER=proharmedic
      - POSTGRES_PASSWORD=9ECDPWD8RWLtrNbmBVW6SSHw
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=2GB"

networks:
  proharmed_net:

volumes:
  proharmed_volume:
  proharmed_db_volume:
